#!/usr/bin/env python3
import argparse
import pathlib
import struct


MAGIC = 0x314E425A
HEADER_SIZE = 32
PAGE_SIZE = 4096
MAX_PAYLOAD_SIZE = PAGE_SIZE * 8
STACK_PAGES = 1
USER_PROGRAM_BASE = 0x400000


def c_identifier(name):
    return "userland_" + "".join(ch if ch.isalnum() else "_" for ch in name) + "_image"


def emit_array(handle, name, data):
    handle.write(f"static const uint8_t {name}[] = {{\n")
    for index in range(0, len(data), 12):
        chunk = data[index:index + 12]
        values = ", ".join(f"0x{value:02x}" for value in chunk)
        handle.write(f"    {values},\n")
    handle.write("};\n\n")


def align_up(value, alignment):
    return (value + alignment - 1) & ~(alignment - 1)


def payload_from_elf(data):
    if len(data) < 64 or data[:4] != b"\x7fELF":
        return 0, data

    if data[4] != 2 or data[5] != 1:
        raise SystemExit("only little-endian ELF64 user programs are supported")

    entry, phoff = struct.unpack_from("<QQ", data, 24)
    phentsize, phnum = struct.unpack_from("<HH", data, 54)
    loads = []

    for index in range(phnum):
        offset = phoff + index * phentsize
        p_type = struct.unpack_from("<I", data, offset)[0]
        if p_type != 1:
            continue

        _, _, p_offset, p_vaddr, _, p_filesz, p_memsz, _ = struct.unpack_from("<IIQQQQQQ", data, offset)
        if p_memsz == 0:
            continue
        if p_vaddr < USER_PROGRAM_BASE:
            raise SystemExit("user program load segment is below USER_PROGRAM_BASE")
        loads.append((p_offset, p_vaddr, p_filesz, p_memsz))

    if not loads:
        raise SystemExit("ELF user program has no loadable segments")

    end = 0
    for _, p_vaddr, _, p_memsz in loads:
        relative_end = p_vaddr - USER_PROGRAM_BASE + p_memsz
        if relative_end > end:
            end = relative_end

    payload = bytearray(align_up(end, PAGE_SIZE))
    for p_offset, p_vaddr, p_filesz, _ in loads:
        relative = p_vaddr - USER_PROGRAM_BASE
        payload[relative:relative + p_filesz] = data[p_offset:p_offset + p_filesz]

    return entry - USER_PROGRAM_BASE, bytes(payload)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("programs", nargs="+", help="name=path pairs")
    args = parser.parse_args()

    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    for item in args.programs:
        name, path = item.split("=", 1)
        entry_offset, payload = payload_from_elf(pathlib.Path(path).read_bytes())
        payload_size = align_up(len(payload), PAGE_SIZE)
        if payload_size > MAX_PAYLOAD_SIZE:
            raise SystemExit(f"{name}: payload is {len(payload)} bytes, limit is {MAX_PAYLOAD_SIZE}")

        payload = payload + bytes(payload_size - len(payload))
        header = struct.pack("<IIQQQ", MAGIC, HEADER_SIZE, entry_offset, payload_size, STACK_PAGES)
        entries.append((name, c_identifier(name), header + payload))

    with output.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("/* Generated by tools/package_userland.py. */\n")
        handle.write("#ifndef ZENITH_INITRAMFS_USERLAND_INC\n")
        handle.write("#define ZENITH_INITRAMFS_USERLAND_INC\n\n")
        for _, identifier, data in entries:
            emit_array(handle, identifier, data)
        handle.write("#endif\n")


if __name__ == "__main__":
    main()
